### ISSUE TITLE
[Fix] MapMark 컴포넌트 중심 좌표 수정

### ISSUE THREAD

**Issue by seokzin** [modorie/moida#107]
## 🐞 문제점

- MapMark 컴포넌트에 라벨이 달리게 되면 중심 좌표가 원을 벗어나요.
- 우리가 좌표 값을 부여했을 때, 마크가 가리키는 좌표가 정확하지 않게 될 수 있어요.

![image](https://user-images.githubusercontent.com/43740455/158738803-bced6c88-d808-45d7-9d68-d245bc5344a2.png)

<br/>

## 🛠 해결방안

- 현재 `<Text>` 컴포넌트의 display가 공간을 차지해서 중심 좌표가 변한 것 같아요.
- absolute + relative 형식으로 관리하면 마크의 중심을 보존할 수 있을까 싶어요.
- 더 좋은 방법이 있다면 그렇게 해주세요!

```jsx
<Mark>
  {children && <Text>{children}</Text>}
</Mark>
```

<br/>

## 🌐 참고 자료

-

**Comment by devpla** [comment]
확인했어요!
