### ISSUE TITLE
[Feat] 스토리북 글로벌 스타일 적용

### ISSUE THREAD

**Issue by devpla** [modorie/moida#23]
## 🚩 요구사항

- 스토리북 전체 컴포넌트에 적용할 글로벌 스타일이 필요해요.

<br/>

## 💡 구현 방안

- `preview.ts` 파일을 이용해서 적용해야해요.
- 그런데 `.ts` 파일 내부에는 jsx 문법을 쓸 수 없어요 😢
- 그래서 `_app.tsx`에서 한 것처럼 `<GlobalStyle />` 로 불러올 수 없어요.
- 어떻게 해결해야 할까요?

<br/>

## 🌐 참고 자료

-

**Comment by seokzin** [comment]
~~스토리북에 Alias가 적용 안되는 것 같아요.. 😥~~

빌드하니까 정상 빌드는 되는데 TS에서 빨간 줄을 띄어주네요..
