### ISSUE TITLE
[Refac] 스토리북의 Meta 타입 명시 

### ISSUE THREAD

**Issue by seokzin** [modorie/moida#64]
## 🚩 요구사항

- 스토리북이 제공하는 Meta 타입을 명시해요.

<br/>

## 💡 구현 방안

- export default 뒤에 as Meta를 명시하면 돼요!

<br/>

## 🌐 참고 자료

- 스토리북 공식 문서

**Comment by devpla** [comment]
가장 최근에 만든 ButtonGroup은 명시해두었어요!

**Comment by devpla** [comment]
as Meta!
