### ISSUE TITLE
[Feat] Icon의 viewBox 속성을 props로 관리

### ISSUE THREAD

**Issue by seokzin** [modorie/moida#99]
## 🚩 요구사항

- 크기가 다른 svg 아이콘을 구현할 때 원본의 크기를 바꾸면 스토리북의 아이콘 크기가 동일하지 않아요.
- 또한 이런 식의 구현은 추후 같은 아이콘을 쓰는 상황에서 문제가 될 가능성이 있구요.

<br/>

## 💡 구현 방안

- viewBox 속성을 props로 관리하면 원본을 유지한 채 커스텀 할 수 있어요.

<br/>

## 🌐 참고 자료

- https://stackoverflow.com/questions/1301685/fixed-stroke-width-in-svg
- size를 변경해도 stroke-width를 유지하는 방법

**Comment by seokzin** [comment]
- viewBox를 prop으로 관리해도 size에 따른 테두리 두께 변화는 여전했어요.
- 그래서 `vector-effect="non-scaling-stroke"`를 통해 다른 방식으로 해결했어요. (#93)

**Comment by devpla** [comment]
고생했어요!
